apps/blog/urls.py
# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

"""Blog URL Configuration."""

from django.urls import path

from . import views
from .feeds import LatestPostsFeedAtom, LatestPostsFeedRSS

app_name = 'blog'

urlpatterns = (
    path('', views.PostListView.as_view(), name='post_list'),

    path('feeds/atom/posts.xml', LatestPostsFeedAtom(), name='posts_atom'),
    path('feeds/rss/posts.xml', LatestPostsFeedRSS(), name='posts_rss'),

    path(
        'post/<int:year>/<int:month>/<int:day>/<slug:slug>.html',
        views.PostDetailView.as_view(),
        name='post_view'
    ),

    path(
        'posts/tagged/<slug:slug>',
        views.PostTaggedView.as_view(),
        name='post_list_by_tag'
    ),
)

apps/telegraph/urls.py
# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

"""Telegraph URL Configuration."""

from django.urls import path

from .views import ContactFormView

app_name = 'telegraph'

urlpatterns = (
    path('contact.html', ContactFormView.as_view(), name='contact_form'),
)

branch/urls.py
# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
#
# This file is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <https://www.gnu.org/licenses/>.

"""branch URL Configuration."""

import os

from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path
from django.views.static import serve

from apps.blog.sitemaps import PostSitemap, PostsListSitemap
from apps.pages.sitemaps import PageSitemap
from apps.telegraph.sitemaps import TelegraphSitemap


def sitemaps():
    """Get whole website sitemap."""
    return {'sitemaps': {
        'page': PageSitemap,
        'telegraph': TelegraphSitemap,
        'post': PostSitemap,
        'post_list': PostsListSitemap,
    }}


handler404 = 'apps.core.views.handler404'
handler500 = 'apps.core.views.handler500'

urlpatterns = [
    # Site-wide URLs.
    path('', include('apps.core.urls', namespace='core')),
    # Blog URLs.
    path('', include('apps.blog.urls', namespace='blog')),
    # Site pages.
    path('', include('apps.pages.urls', namespace='pages')),
    # Contacts.
    path('', include('apps.telegraph.urls', namespace='telegraph')),
    # Comments.
    re_path(r'^comments/', include('apps.comments.urls')),
    # Blog admin.
    path(f'{settings.ADMIN_SITE_URL}/', admin.site.urls),
    # Sitemaps.
    path('sitemap.xml', sitemap, sitemaps(), name='sitemap'),
]

if settings.DEBUG:
    import debug_toolbar  # pylint: disable=E0401

    # Static & media files for development environment
    static_routes = [
        re_path(
            fr"^{settings.STATIC_URL.strip('/')}/(?P<path>.*)$",
            serve,
            {'document_root': settings.STATIC_ROOT}
        ),
        re_path(
            fr"^{settings.MEDIA_URL.strip('/')}/(?P<path>.*)$",
            serve,
            {'document_root': settings.MEDIA_ROOT}
        )
    ]

    icons = [
        # Some browsers requests for icons from the site root, despite meta
        # tags definition.
        re_path(
            r'^(?P<path>favicon\.ico|apple-touch-icon.*\.png)$',
            serve,
            {'document_root': f'{settings.STATIC_ROOT}/icons'},
        ),

        # The following action icons are hardcoded in Django source code
        #
        # '../img/icon-viewlink.svg'
        # '../img/icon-addlink.svg'
        # '../img/icon-changelink.svg'
        # '../img/icon-deletelink.svg
        #
        # And when sending requests to '/<ADMIN_URL>/<APP>/<MODEL>/', Safari
        # makes request to the following URLS
        # '/<ADMIN_URL>/<MODEL>/img/icon-.*.svg' due to relative nature of
        # icons links.
        #
        # Refs:
        #    - django/contrib/admin/static/admin/css/base.css
        #    - https://discussions.apple.com/thread/1407049
        #
        re_path(
            r'^.*/(?P<path>img/icon-.*.svg)$',
            serve,
            {'document_root': os.path.join(settings.STATIC_ROOT, 'admin')}
        ),
    ]

    debug = [
        path('__debug__/', include(debug_toolbar.urls))
    ]

    urlpatterns = static_routes + icons + debug + urlpatterns

templates/partials/branch-data.html
<script type="application/json" id="branch-data">
    {
        "analytics_code": "{{ GA_TRACKING_ID|default:'' }}",
        "site_name": "{{ SITE_NAME }}",
        "language": "{{ LANG }}",
        "language_short": "{{ LANG_SHORT }}",
        "language_lower": "{{ LANG_LOWER }}",
        "locale": "{{ LOCALE }}",
        "dir": "{{ DIR }}"
    }
</script>

templates/partials/canonical-url.html
<link rel="canonical" href="{{ SITE_URL }}{{ resource_url|default:request.path }}">

templates/partials/dc-metadata.html
{% load seo_helpers locale_helpers %}

<meta property="dc:title" content="{{ seo_title|default:SITE_NAME }}">
{% if seo_description and seo_description.strip %}
    <meta property="dc:description" content="{{ seo_description|sanitize_description }}">
{% else %}
    <meta property="dc:description" content="{{ SITE_DESCRIPTION|sanitize_description }}">
{% endif %}
<meta property="dc:creator" content="{{ seo_author|default:SITE_NAME }}">
<meta property="dc:contributor" content="{{ seo_author|default:SITE_NAME }}">
<meta property="dc:type" content="Text">
{% if seo_locale and seo_locale.strip %}
    <meta property="dc:language" content="{{ seo_locale|to_language }}">
{% else %}
    <meta property="dc:language" content="{{ LANG }}">
{% endif %}
{% if page_rights and page_rights.strip %}
    {# TODO: Add to Page model property #}
    <meta property="dc:rights" content="{{ page_rights }}">
{% endif %}
    <meta property="dc:identifier" content="{{ SITE_URL }}{{ resource_url|default:request.path }}">

templates/partials/messages.html
{% if messages %}
    <ul class="feedback-message" id="feedback-message" style="margin-top: 3em">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                {{ message }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/mini-toc.html
{% load i18n blog_posts %}

<h2>{% trans 'Latest publications' %}</h2>

<div class="toc" role="navigation">
    {% show_latest_posts 5 %}

    {% total_posts as total_published_posts %}
    {% if total_published_posts > 5 %}
        <p>
            <a href="{% url 'blog:post_list' %}">
                <span aria-hidden="true">&larr;</span>
                {% trans 'All posts' %}
            </a>
        </p>
    {% endif %}
</div>

templates/partials/og-metadata.html
{% load static seo_helpers %}

<meta property="og:url" content="{{ SITE_URL }}{{ resource_url|default:request.path }}">
<meta property="og:type" content="{{ resource_type|default:'website' }}">
{% block og_article %}{% endblock %}
<meta property="og:title" content="{{ seo_title|default:SITE_NAME }}">

{% if seo_description and seo_description.strip %}
    <meta property="og:description" content="{{ seo_description|sanitize_description }}">
{% else %}
    <meta property="og:description" content="{{ SITE_DESCRIPTION|sanitize_description }}">
{% endif %}

<meta property="og:site_name" content="{{ SITE_NAME }}">

{% if seo_locale and seo_locale.strip %}
    <meta property="og:locale" content="{{ seo_locale }}">
{% else %}
    <meta property="og:locale" content="{{ LOCALE }}">
{% endif %}

{% if featured_image %}
    <meta property="og:image" content="{{ SITE_URL }}{{ featured_image.url }}">
{% else%}
    <meta property="og:image" content="{{ SITE_URL }}{% static 'img/blog-logo.jpg' %}">
    <meta property="og:image:width" content="400">
    <meta property="og:image:height" content="400">
{% endif %}

<meta property="og:image:alt" content="{{ seo_title|default:SITE_NAME }}">

templates/partials/page-description.html
{% load seo_helpers %}

{% if seo_description and seo_description.strip %}
    <meta name="description" content="{{ seo_description|sanitize_description }}">
{% else %}
    <meta name="description" content="{{ SITE_DESCRIPTION|sanitize_description }}">
{% endif %}

templates/partials/sidebar.html
{% load i18n static %}

<input type="checkbox" class="sidebar-checkbox" id="sidebar-checkbox">

<aside class="sidebar sidebar-image sidebar-image-on"
       id="sidebar"
       style="background-image: url({% static 'img/dark-forest.jpg' %});">
    <div class="sidebar-item">
        <p>{{ SITE_DESCRIPTION }}</p>
    </div>

    <nav class="sidebar-nav">
        {# TODO: resolve active class #}
        <a class="sidebar-nav-item" href="{% url 'blog:post_list' %}">
            {% trans 'Blog' %}
        </a>
        <a class="sidebar-nav-item" href="{% url 'telegraph:contact_form' %}">
            {% trans 'Contact Form' %}
        </a>
        {% for p in pages %}
            <a class="sidebar-nav-item" href="{{ p.get_absolute_url }}">
                {{ p.title }}
            </a>
        {% endfor %}

        {# TODO: Implement me #}
        {# <a class="sidebar-nav-item" href="/search.html"> #}
            {# {% trans 'Search' %} #}
        {# </a> #}

        <div class="sidebar-nav-item">
            <a href="{% url 'blog:posts_atom' %}" title="{% trans 'Subscribe to posts (Atom)' %}">Atom</a>
            <span aria-hidden="true">|</span>
            <a href="{% url 'blog:posts_rss' %}" title="{% trans 'Subscribe to posts (RSS 2.0)' %}">RSS 2.0</a>
        </div>

        <a class="sidebar-nav-item" href="https://github.com/{{ GITHUB_USER }}" target="_blank">
            {% trans 'GitHub Profile' %}
        </a>
    </nav>

    <div class="sidebar-item">
        <p>
            &copy; {{ COPYRIGHT_HOLDER }} 2018-{% now "Y" %}.
            {% trans 'Unless otherwise stated, all content on the site is available under' %}
            <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" rel="license" target="_blank">
                CC BY-NC-SA 4.0
            </a>&nbsp;.
        </p>
    </div>
</aside>

templates/partials/twitter-metadata.html
{% load static seo_helpers %}

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{{ seo_title|default:SITE_NAME }}">

{% if seo_description and seo_description.strip %}
    <meta name="twitter:description" content="{{ seo_description|sanitize_description }}">
{% else %}
    <meta name="twitter:description" content="{{ SITE_DESCRIPTION|sanitize_description }}">
{% endif %}

{% if featured_image %}
    <meta name="twitter:image:src" content="{{ SITE_URL }}{{ featured_image.url }}">
{% else%}
    <meta name="twitter:image:src" content="{{ SITE_URL }}{% static 'img/blog-logo.jpg' %}">
{% endif %}

<meta name="twitter:image:alt" content="{{ seo_title|default:SITE_NAME }}">